version: "3.8"
services:
  app:
    container_name: credit-analysis
    build:
      dockerfile: Dockerfile
    image: "allancordeiros/credit-analysis:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - postgres
    command: sh -c dockerize -wait tcp://postgres:5432 -timeout 20s java -jar credit-analysis.jar
  postgres:
    container_name: "pgloanapp"
    image: postgres:14.1-alpine
    restart: always
    tty: true
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bduser
      - POSTGRES_PASSWORD=bdpassword
      - POSTGRES_DB=loan-app
    networks:
      - spring-cloud-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "9000:80"
    depends_on:
      - postgres
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge